
GET http://localhost:3000/user
Content-Type: application/json

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "adolfo@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
	"name": "adolfo",
	"lastName": "zuazo",
	"dni": "37525727",
	"fec_nac": "30/08/93",
	"sex": "masculino",
	"password": "123456",
	"email": "adolfo@gmail.com",
	"rol": ["user"]
}

###

PUT http://localhost:3000/user/5f8c8fd05c777917003f4426
Content-Type: application/json

{
	"name": "adolfo123"
}

