
GET http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmOGY3NWZjN2M2NjQ0MTQzNGU3OThhNiIsIm5hbWUiOiJBZG9sZm8iLCJsYXN0TmFtZSI6Ilp1YXpvIiwiZG5pIjoiMzc1MjU3MjciLCJmZWNfbmFjIjoiMTk5My0wOC0zMCIsInNleCI6Im1hc2N1bGlubyIsInBhc3N3b3JkIjoiJDJiJDEwJGMzR0FOc1VCMkh2MzRTTklZY0xiMXVGUUwyQkIxSmtiaWJURld5eTZ1NHpsUEdlZXRUNlhpIiwiZW1haWwiOiJhZG9sZm9AZ21haWwuY29tIiwicm9sIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIwLTEwLTIwVDIzOjQyOjUyLjI1OVoiLCJ1cGRhdGVkQXQiOiIyMDIwLTEwLTIwVDIzOjQyOjUyLjI1OVoiLCJfX3YiOjB9LCJpYXQiOjE2MDMyOTE4NTksImV4cCI6MTYwMzI5NTQ1OX0.Ey94-WGqj2leFXEFK9E2VutmESEzPl6TL-qkiyDqRsg

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "adolfo@gmail.com",
    "password": "37525727"
}

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
	"name": "adolfo",
	"lastName": "zuazo",
	"dni": "37525727",
	"fec_nac": "30/08/93",
	"sex": "masculino",
	"password": "123456",
	"email": "adolfo@gmail.com",
	"rol": ["user"]
}

###

PUT http://localhost:3000/user/5f8c8fd05c777917003f4426
Content-Type: application/json

{
	"name": "adolfo123"
}

